CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Ingredients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "NameSearchVector" tsvector GENERATED ALWAYS AS (to_tsvector('russian', "Name")) STORED,
    CONSTRAINT "PK_Ingredients" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Ingredients_NameSearchVector" ON "Ingredients" USING GIN ("NameSearchVector");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220814065937_InitialMigration', '6.0.7');

COMMIT;

